sudo: required
dist: trusty
addons:
  apt:
    packages:
    - texlive-fonts-recommended
    - texlive-latex-extra
    - texlive-fonts-extra
    - dvipng
    - texlive-latex-recommended
    - texlive-lang-german
    - texlive-science
    - pdftk
    - ghostscript
script:
- make web
- make druck
- make fast
# make archive is not tested due to copyright restrictions on the MathPhys stationery
deploy:
  provider: releases
  api_key:
    secure: [YOUR KEY]
  file:
  - vorschau_inhalt.pdf
  skip_cleanup: true
  on:
    tags: true
